environmental_charges = float(input("Environmental Charges (20% of Basic Charge):"))
maintenance_charge = float(input("Maintenance Service Charge (MSC): "))
charges_before_taxes = float(input("Total Current Charges Before Taxes: "))
government_taxes = float(input("Government Taxes: "))
payment_due_date = input("Payment Due Date: ")